### ISSUE TITLE
Application V3

### ISSUE THREAD

**Issue by ghost** [phirecms/phirecms#1]
Hello, nice framework but why for Version3 the application is missing?

**Comment by nicksagona** [comment]
V3 was started about 6 months ago, but work on it stopped for the time being b/c of a couple of factors. Mainly, I want to look into significantly changing the structure of the CMS, making it more of a headless or decoupled CMS with an API. Also, I just haven't had as much time to work on it in my free time as I used to. Hoping to possibly get back on it sometime this year.

Thanks for your interest in Phire.

**Comment by ghost** [comment]
Hello,
I tried to convert the CMS in version 3 without success.

Sin. Another beautiful project that died before it was even born.

Step further. Thanks for the reply.
